apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '8'
  generation: 20
  labels:
    app: <k8s-label>
  name:  <k8s-label>
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app:  <k8s-label>
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  <k8s-label>
    spec:
      containers:
        - image: "mydocker-registry.com/<IMG_NAME>:<IMG_TAG>"
          imagePullPolicy: Always
          name:  <k8s-label>
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: aliyun_logs_ryan-miao-access-prod
              value: "/tmp/logs/ryan-miao-app*.log"
            - name: aliyun_logs_ryan-miao-access-prod_format
              value: "json"
            - name: aliyun_logs_ryan-miao-access-prod_tags
              value: "service=<k8s-label>,env=prod"
            - name: SW_AGENT_NAMESPACE
              value: "ryan-miao-prod"
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "192.168.81.41:11800"
            - name: SW_AGENT_NAME
              value: "<k8s-label>"
            - name: SW_AGENT_SAMPLE
              value: "0"
          volumeMounts:
            - name: app-log
              mountPath: /tmp/logs
      volumes:
        - name: app-log
          emptyDir: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: docker-login-secrets
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30


